/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint with API info.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Status
         * @description Check if authentication is required.
         *
         *     Public endpoint - frontend uses this to determine if login is needed.
         */
        get: operations["auth_status_api_v1_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Session Login
         * @description Login with username and optional password, get session cookie.
         *
         *     Creates a session and sets an HTTP-only secure cookie.
         *     Frontend should redirect here if no valid session exists.
         */
        post: operations["session_login_api_v1_auth_session_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Session Logout
         * @description Logout and clear session cookie.
         *
         *     Deletes the session from storage and clears the cookie.
         */
        post: operations["session_logout_api_v1_auth_session_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Me
         * @description Get current session info.
         *
         *     Returns the username from the current session.
         *     Requires valid session (enforced by middleware).
         */
        get: operations["session_me_api_v1_auth_session_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Upload a CSV file for processing.
         *
         *     The file will be parsed, validated, and stored in the database.
         *     Activity data will be extracted and made available for analysis.
         */
        post: operations["upload_file_api_v1_files_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File Api
         * @description Upload a CSV file using API key authentication.
         *
         *     This endpoint is designed for programmatic/pipeline uploads.
         *     Uses X-Api-Key header for authentication instead of site password.
         *
         *     The file will be parsed, validated, and stored in the database.
         *     Activity data will be extracted and made available for analysis.
         */
        post: operations["upload_file_api_api_v1_files_upload_api_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description List all uploaded files with pagination.
         */
        get: operations["list_files_api_v1_files_get"];
        put?: never;
        post?: never;
        /**
         * Delete All Files
         * @description Delete all files from the database.
         *
         *     Optionally filter by status (e.g., 'failed' to delete only failed files).
         */
        delete: operations["delete_all_files_api_v1_files_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Get file metadata by ID.
         */
        get: operations["get_file_api_v1_files__file_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete File
         * @description Delete a file and its associated data.
         */
        delete: operations["delete_file_api_v1_files__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File Dates
         * @description Get available dates for a file.
         */
        get: operations["get_file_dates_api_v1_files__file_id__dates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Data Directory
         * @description Start a background scan of the data directory for CSV files.
         *
         *     Files already in the database are skipped.
         *     Returns immediately with scan status - poll GET /scan/status for progress.
         */
        post: operations["scan_data_directory_api_v1_files_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/scan/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Status
         * @description Get the current status of the background file scan.
         *
         *     Poll this endpoint to track import progress.
         */
        get: operations["get_scan_status_api_v1_files_scan_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/watcher/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watcher Status
         * @description Get the current status of the automatic file watcher.
         *
         *     The file watcher monitors the data directory for new CSV files
         *     and automatically ingests them into the database.
         */
        get: operations["get_watcher_status_api_v1_files_watcher_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/{file_id}/{analysis_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity Data
         * @description Get activity data for a specific file and date.
         *
         *     Returns data in columnar format for efficient transfer.
         *     The view window starts from analysis_date at 12:00 (noon) and extends for view_hours.
         */
        get: operations["get_activity_data_api_v1_activity__file_id___analysis_date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/{file_id}/{analysis_date}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity Data With Scoring
         * @description Get activity data with sleep scoring algorithm results.
         *
         *     Returns data with:
         *     - Sleep scoring results (1=sleep, 0=wake)
         *     - Choi nonwear detection results (1=nonwear, 0=wear)
         *
         *     Available algorithms:
         *     - sadeh_1994_actilife (default): Sadeh 1994 with ActiLife scaling
         *     - sadeh_1994_original: Sadeh 1994 original paper version
         *     - cole_kripke_1992_actilife: Cole-Kripke 1992 with ActiLife scaling
         *     - cole_kripke_1992_original: Cole-Kripke 1992 original paper version
         */
        get: operations["get_activity_data_with_scoring_api_v1_activity__file_id___analysis_date__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/{file_id}/{analysis_date}/sadeh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity Data With Sadeh
         * @description Get activity data with Sadeh algorithm results.
         *
         *     DEPRECATED: Use /{file_id}/{analysis_date}/score?algorithm=sadeh_1994_actilife instead.
         */
        get: operations["get_activity_data_with_sadeh_api_v1_activity__file_id___analysis_date__sadeh_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markers/{file_id}/{analysis_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Markers
         * @description Get all markers for a specific file and date.
         *
         *     Returns sleep markers, nonwear markers, and calculated metrics.
         *     Optionally includes algorithm results for overlay display.
         */
        get: operations["get_markers_api_v1_markers__file_id___analysis_date__get"];
        /**
         * Save Markers
         * @description Save markers for a specific file and date.
         *
         *     Replaces all existing markers for this file/date with the new ones.
         *     Triggers background calculation of sleep metrics.
         */
        put: operations["save_markers_api_v1_markers__file_id___analysis_date__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markers/{file_id}/{analysis_date}/{period_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Marker
         * @description Delete a specific marker period.
         */
        delete: operations["delete_marker_api_v1_markers__file_id___analysis_date___period_index__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markers/{file_id}/{analysis_date}/adjacent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Adjacent Day Markers
         * @description Get sleep markers from previous and next days.
         *
         *     Used to show continuity of sleep across day boundaries.
         */
        get: operations["get_adjacent_day_markers_api_v1_markers__file_id___analysis_date__adjacent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markers/{file_id}/{analysis_date}/table/{period_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Onset Offset Data
         * @description Get activity data around a marker for onset/offset tables.
         *
         *     Returns data points within window_minutes of the onset and offset timestamps.
         */
        get: operations["get_onset_offset_data_api_v1_markers__file_id___analysis_date__table__period_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markers/{file_id}/{analysis_date}/table-full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Full Table Data
         * @description Get full 48h of activity data for popout table display.
         *
         *     Returns all epochs from noon of analysis_date to noon of next day.
         *     Includes algorithm results and nonwear detection.
         */
        get: operations["get_full_table_data_api_v1_markers__file_id___analysis_date__table_full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Export Columns
         * @description Get list of available export columns.
         *
         *     Returns all available columns with their metadata, grouped by category.
         */
        get: operations["get_export_columns_api_v1_export_columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Csv Export
         * @description Generate CSV export for specified files.
         *
         *     Returns metadata about the export. Use /csv/download to get the actual file.
         */
        post: operations["generate_csv_export_api_v1_export_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/csv/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download Csv Export
         * @description Generate and download CSV export.
         *
         *     Returns the CSV file directly as a download.
         */
        post: operations["download_csv_export_api_v1_export_csv_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/csv/quick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quick Export
         * @description Quick export endpoint for simple GET requests.
         *
         *     Uses default columns and returns CSV directly.
         */
        get: operations["quick_export_api_v1_export_csv_quick_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diary/{file_id}/{analysis_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diary Entry
         * @description Get diary entry for a specific file and date.
         *
         *     Returns None if no diary entry exists for the given file/date.
         */
        get: operations["get_diary_entry_api_v1_diary__file_id___analysis_date__get"];
        /**
         * Update Diary Entry
         * @description Create or update a diary entry for a specific file and date.
         */
        put: operations["update_diary_entry_api_v1_diary__file_id___analysis_date__put"];
        post?: never;
        /**
         * Delete Diary Entry
         * @description Delete a diary entry.
         */
        delete: operations["delete_diary_entry_api_v1_diary__file_id___analysis_date__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diary/{file_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Diary Csv
         * @description Upload a diary CSV file to import entries for a specific activity file.
         *
         *     Expected CSV columns (case-insensitive):
         *     - date: Analysis date (YYYY-MM-DD or MM/DD/YYYY)
         *     - bed_time: Time went to bed (HH:MM)
         *     - wake_time: Time woke up (HH:MM)
         *     - lights_out: Time lights were turned off (optional)
         *     - got_up: Time got out of bed (optional)
         *     - sleep_quality: Quality rating 1-5 or 1-10 (optional)
         *     - time_to_fall_asleep: Minutes to fall asleep (optional)
         *     - awakenings: Number of awakenings (optional)
         *     - notes: Free text notes (optional)
         */
        post: operations["upload_diary_csv_api_v1_diary__file_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Get current user's settings.
         *
         *     Returns default settings if no settings have been saved yet.
         */
        get: operations["get_settings_api_v1_settings_get"];
        /**
         * Update Settings
         * @description Update current user's settings.
         *
         *     Creates settings record if it doesn't exist.
         *     Only updates fields that are provided (non-None).
         */
        put: operations["update_settings_api_v1_settings_put"];
        post?: never;
        /**
         * Reset Settings
         * @description Reset user settings to defaults.
         *
         *     Deletes the settings record, so next GET will return defaults.
         */
        delete: operations["reset_settings_api_v1_settings_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityDataColumnar
         * @description Columnar format for efficient JSON transfer.
         *
         *     This format reduces JSON overhead by using arrays instead of
         *     repeated object keys for each data point.
         */
        ActivityDataColumnar: {
            /**
             * Timestamps
             * @description Unix timestamps
             */
            timestamps?: number[];
            /** Axis X */
            axis_x?: number[];
            /** Axis Y */
            axis_y?: number[];
            /** Axis Z */
            axis_z?: number[];
            /** Vector Magnitude */
            vector_magnitude?: number[];
        };
        /**
         * ActivityDataResponse
         * @description Response for activity data endpoint.
         */
        ActivityDataResponse: {
            data: components["schemas"]["ActivityDataColumnar"];
            /** Available Dates */
            available_dates?: string[];
            /**
             * Current Date Index
             * @default 0
             */
            current_date_index: number;
            /** Algorithm Results */
            algorithm_results?: number[] | null;
            /** Nonwear Results */
            nonwear_results?: number[] | null;
            /** File Id */
            file_id: number;
            /** Analysis Date */
            analysis_date: string;
            /** View Start */
            view_start?: number | null;
            /** View End */
            view_end?: number | null;
            /**
             * Sensor Nonwear Periods
             * @default []
             */
            sensor_nonwear_periods?: components["schemas"]["SensorNonwearPeriod"][];
        };
        /**
         * AdjacentDayMarkersResponse
         * @description Response with markers from previous and next days.
         */
        AdjacentDayMarkersResponse: {
            /** Previous Day Markers */
            previous_day_markers?: components["schemas"]["SleepPeriod"][];
            /** Next Day Markers */
            next_day_markers?: components["schemas"]["SleepPeriod"][];
            /** Previous Date */
            previous_date?: string | null;
            /** Next Date */
            next_date?: string | null;
        };
        /**
         * AlgorithmType
         * @description Sleep scoring algorithm identifiers.
         *
         *     These values match the algorithm IDs registered in AlgorithmFactory.
         * @enum {string}
         */
        AlgorithmType: "sadeh_1994_original" | "sadeh_1994_actilife" | "cole_kripke_1992_original" | "cole_kripke_1992_actilife" | "manual";
        /**
         * AuthStatusResponse
         * @description Response for auth status check.
         */
        AuthStatusResponse: {
            /**
             * Password Required
             * @description Whether password is required
             */
            password_required: boolean;
        };
        /** Body_upload_diary_csv_api_v1_diary__file_id__upload_post */
        Body_upload_diary_csv_api_v1_diary__file_id__upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_file_api_api_v1_files_upload_api_post */
        Body_upload_file_api_api_v1_files_upload_api_post: {
            /**
             * File
             * Format: binary
             * @description CSV file to upload
             */
            file: string;
        };
        /** Body_upload_file_api_v1_files_upload_post */
        Body_upload_file_api_v1_files_upload_post: {
            /**
             * File
             * Format: binary
             * @description CSV file to upload
             */
            file: string;
        };
        /**
         * DiaryEntryCreate
         * @description Request model for creating/updating a diary entry.
         */
        DiaryEntryCreate: {
            /** Bed Time */
            bed_time?: string | null;
            /** Wake Time */
            wake_time?: string | null;
            /** Lights Out */
            lights_out?: string | null;
            /** Got Up */
            got_up?: string | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Time To Fall Asleep Minutes */
            time_to_fall_asleep_minutes?: number | null;
            /** Number Of Awakenings */
            number_of_awakenings?: number | null;
            /** Notes */
            notes?: string | null;
            /** Nap 1 Start */
            nap_1_start?: string | null;
            /** Nap 1 End */
            nap_1_end?: string | null;
            /** Nap 2 Start */
            nap_2_start?: string | null;
            /** Nap 2 End */
            nap_2_end?: string | null;
            /** Nap 3 Start */
            nap_3_start?: string | null;
            /** Nap 3 End */
            nap_3_end?: string | null;
            /** Nonwear 1 Start */
            nonwear_1_start?: string | null;
            /** Nonwear 1 End */
            nonwear_1_end?: string | null;
            /** Nonwear 1 Reason */
            nonwear_1_reason?: string | null;
            /** Nonwear 2 Start */
            nonwear_2_start?: string | null;
            /** Nonwear 2 End */
            nonwear_2_end?: string | null;
            /** Nonwear 2 Reason */
            nonwear_2_reason?: string | null;
            /** Nonwear 3 Start */
            nonwear_3_start?: string | null;
            /** Nonwear 3 End */
            nonwear_3_end?: string | null;
            /** Nonwear 3 Reason */
            nonwear_3_reason?: string | null;
        };
        /**
         * DiaryEntryResponse
         * @description Response model for a single diary entry.
         */
        DiaryEntryResponse: {
            /** Id */
            id: number;
            /** File Id */
            file_id: number;
            /**
             * Analysis Date
             * Format: date
             */
            analysis_date: string;
            /** Bed Time */
            bed_time?: string | null;
            /** Wake Time */
            wake_time?: string | null;
            /** Lights Out */
            lights_out?: string | null;
            /** Got Up */
            got_up?: string | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Time To Fall Asleep Minutes */
            time_to_fall_asleep_minutes?: number | null;
            /** Number Of Awakenings */
            number_of_awakenings?: number | null;
            /** Notes */
            notes?: string | null;
            /** Nap 1 Start */
            nap_1_start?: string | null;
            /** Nap 1 End */
            nap_1_end?: string | null;
            /** Nap 2 Start */
            nap_2_start?: string | null;
            /** Nap 2 End */
            nap_2_end?: string | null;
            /** Nap 3 Start */
            nap_3_start?: string | null;
            /** Nap 3 End */
            nap_3_end?: string | null;
            /** Nonwear 1 Start */
            nonwear_1_start?: string | null;
            /** Nonwear 1 End */
            nonwear_1_end?: string | null;
            /** Nonwear 1 Reason */
            nonwear_1_reason?: string | null;
            /** Nonwear 2 Start */
            nonwear_2_start?: string | null;
            /** Nonwear 2 End */
            nonwear_2_end?: string | null;
            /** Nonwear 2 Reason */
            nonwear_2_reason?: string | null;
            /** Nonwear 3 Start */
            nonwear_3_start?: string | null;
            /** Nonwear 3 End */
            nonwear_3_end?: string | null;
            /** Nonwear 3 Reason */
            nonwear_3_reason?: string | null;
        };
        /**
         * DiaryUploadResponse
         * @description Response after uploading diary CSV.
         */
        DiaryUploadResponse: {
            /** Entries Imported */
            entries_imported: number;
            /** Entries Skipped */
            entries_skipped: number;
            /** Errors */
            errors: string[];
        };
        /**
         * ExportColumnCategory
         * @description Category of export columns (e.g., Participant Info, Sleep Metrics).
         */
        ExportColumnCategory: {
            /**
             * Name
             * @description Category display name
             */
            name: string;
            /**
             * Columns
             * @description Column names in this category
             */
            columns?: string[];
        };
        /**
         * ExportColumnInfo
         * @description Information about an available export column.
         */
        ExportColumnInfo: {
            /**
             * Name
             * @description Column name as it appears in CSV
             */
            name: string;
            /**
             * Category
             * @description Category for grouping in UI
             */
            category: string;
            /**
             * Description
             * @description Human-readable description
             */
            description?: string | null;
            /**
             * Data Type
             * @description Data type: string, number, datetime
             * @default string
             */
            data_type: string;
            /**
             * Is Default
             * @description Whether included in default export
             * @default true
             */
            is_default: boolean;
        };
        /**
         * ExportColumnsResponse
         * @description Response listing all available export columns.
         */
        ExportColumnsResponse: {
            /** Columns */
            columns?: components["schemas"]["ExportColumnInfo"][];
            /** Categories */
            categories?: components["schemas"]["ExportColumnCategory"][];
        };
        /**
         * ExportRequest
         * @description Request to generate a CSV export.
         */
        ExportRequest: {
            /**
             * File Ids
             * @description File IDs to include in export
             */
            file_ids: number[];
            /**
             * Date Range
             * @description Optional date range filter
             */
            date_range?: [
                string,
                string
            ] | null;
            /**
             * Columns
             * @description Columns to include (None = all)
             */
            columns?: string[] | null;
            /**
             * Include Header
             * @description Include CSV header row
             * @default true
             */
            include_header: boolean;
            /**
             * Include Metadata
             * @description Include metadata comments at top
             * @default false
             */
            include_metadata: boolean;
            /**
             * Export Nonwear Separate
             * @description Export nonwear markers to separate file
             * @default false
             */
            export_nonwear_separate: boolean;
        };
        /**
         * ExportResponse
         * @description Response after generating an export.
         */
        ExportResponse: {
            /** Success */
            success: boolean;
            /** Filename */
            filename?: string | null;
            /**
             * Row Count
             * @default 0
             */
            row_count: number;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * FileInfo
         * @description File metadata for listing.
         */
        FileInfo: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Original Path */
            original_path?: string | null;
            /**
             * File Type
             * @default csv
             */
            file_type: string;
            /** @default pending */
            status: components["schemas"]["FileStatus"];
            /** Row Count */
            row_count?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Uploaded By */
            uploaded_by?: string | null;
            /** Uploaded At */
            uploaded_at?: string | null;
        };
        /**
         * FileStatus
         * @description File processing status.
         * @enum {string}
         */
        FileStatus: "pending" | "processing" | "ready" | "failed";
        /**
         * FileUploadResponse
         * @description Response after file upload.
         */
        FileUploadResponse: {
            /** File Id */
            file_id: number;
            /** Filename */
            filename: string;
            status: components["schemas"]["FileStatus"];
            /** Row Count */
            row_count?: number | null;
            /**
             * Message
             * @default File uploaded successfully
             */
            message: string;
        };
        /**
         * FullTableDataPoint
         * @description Single data point for full 48h table.
         */
        FullTableDataPoint: {
            /** Timestamp */
            timestamp: number;
            /** Datetime Str */
            datetime_str: string;
            /** Axis Y */
            axis_y: number;
            /** Vector Magnitude */
            vector_magnitude: number;
            /** Algorithm Result */
            algorithm_result?: number | null;
            /** Choi Result */
            choi_result?: number | null;
            /**
             * Is Nonwear
             * @default false
             */
            is_nonwear: boolean;
        };
        /**
         * FullTableResponse
         * @description Response with full 48h of data for popout table.
         */
        FullTableResponse: {
            /** Data */
            data?: components["schemas"]["FullTableDataPoint"][];
            /**
             * Total Rows
             * @default 0
             */
            total_rows: number;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ManualNonwearPeriod
         * @description Individual manual nonwear period with timestamps.
         *
         *     Ported from desktop's dataclasses_markers.ManualNonwearPeriod.
         */
        ManualNonwearPeriod: {
            /** Start Timestamp */
            start_timestamp?: number | null;
            /** End Timestamp */
            end_timestamp?: number | null;
            /**
             * Marker Index
             * @default 1
             */
            marker_index: number;
            /** @default manual */
            source: components["schemas"]["NonwearDataSource"];
        };
        /**
         * MarkerCategory
         * @description Category of marker for styling and routing.
         * @enum {string}
         */
        MarkerCategory: "sleep" | "nonwear";
        /**
         * MarkerType
         * @description Sleep marker type classifications.
         * @enum {string}
         */
        MarkerType: "MAIN_SLEEP" | "NAP";
        /**
         * MarkerUpdateRequest
         * @description Request to update markers for a file/date.
         */
        MarkerUpdateRequest: {
            /** Sleep Markers */
            sleep_markers?: components["schemas"]["SleepPeriod"][] | null;
            /** Nonwear Markers */
            nonwear_markers?: components["schemas"]["ManualNonwearPeriod"][] | null;
            algorithm_used?: components["schemas"]["AlgorithmType"] | null;
            /** Detection Rule */
            detection_rule?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Is No Sleep
             * @default false
             */
            is_no_sleep: boolean;
            /**
             * Needs Consensus
             * @default false
             */
            needs_consensus: boolean;
        };
        /**
         * MarkersWithMetricsResponse
         * @description Response with markers and their calculated metrics.
         */
        MarkersWithMetricsResponse: {
            /** Notes */
            notes?: string | null;
            /** Sleep Markers */
            sleep_markers?: components["schemas"]["SleepPeriod"][];
            /** Nonwear Markers */
            nonwear_markers?: components["schemas"]["ManualNonwearPeriod"][];
            /** Metrics */
            metrics?: components["schemas"]["SleepMetrics"][];
            /** Algorithm Results */
            algorithm_results?: number[] | null;
            /** @default draft */
            verification_status: components["schemas"]["VerificationStatus"];
            /** Last Modified At */
            last_modified_at?: string | null;
            /**
             * Is Dirty
             * @default false
             */
            is_dirty: boolean;
            /**
             * Is No Sleep
             * @default false
             */
            is_no_sleep: boolean;
            /**
             * Needs Consensus
             * @default false
             */
            needs_consensus: boolean;
        };
        /**
         * NonwearDataSource
         * @description Nonwear data source types.
         * @enum {string}
         */
        NonwearDataSource: "choi_algorithm" | "manual";
        /**
         * OnsetOffsetDataPoint
         * @description Single data point for onset/offset tables.
         */
        OnsetOffsetDataPoint: {
            /** Timestamp */
            timestamp: number;
            /** Datetime Str */
            datetime_str: string;
            /** Axis Y */
            axis_y: number;
            /** Vector Magnitude */
            vector_magnitude: number;
            /** Algorithm Result */
            algorithm_result?: number | null;
            /** Choi Result */
            choi_result?: number | null;
            /**
             * Is Nonwear
             * @default false
             */
            is_nonwear: boolean;
        };
        /**
         * OnsetOffsetTableResponse
         * @description Response with data points around a marker for tables.
         */
        OnsetOffsetTableResponse: {
            /** Onset Data */
            onset_data?: components["schemas"]["OnsetOffsetDataPoint"][];
            /** Offset Data */
            offset_data?: components["schemas"]["OnsetOffsetDataPoint"][];
            /** Period Index */
            period_index: number;
        };
        /** PaginatedResponse[FileInfo] */
        PaginatedResponse_FileInfo_: {
            /** Items */
            items: components["schemas"]["FileInfo"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Pages
             * @description Total number of pages.
             */
            readonly pages: number;
            /**
             * Has Next
             * @description Whether there is a next page.
             */
            readonly has_next: boolean;
            /**
             * Has Prev
             * @description Whether there is a previous page.
             */
            readonly has_prev: boolean;
        };
        /**
         * SaveStatusResponse
         * @description Response after saving markers.
         */
        SaveStatusResponse: {
            /** Success */
            success: boolean;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            /** Sleep Marker Count */
            sleep_marker_count: number;
            /** Nonwear Marker Count */
            nonwear_marker_count: number;
            /**
             * Message
             * @default Markers saved successfully
             */
            message: string;
        };
        /**
         * SessionLoginRequest
         * @description Request body for session-based login.
         */
        SessionLoginRequest: {
            /** Username */
            username: string;
            /**
             * Password
             * @description Site password. Required if SITE_PASSWORD is configured.
             */
            password?: string | null;
        };
        /**
         * SessionLoginResponse
         * @description Response from session login.
         */
        SessionLoginResponse: {
            /**
             * Success
             * @description Whether login was successful
             */
            success: boolean;
            /**
             * Username
             * @description The logged-in username
             */
            username: string;
            /**
             * Expires In Seconds
             * @description Session lifetime in seconds
             */
            expires_in_seconds: number;
        };
        /**
         * SleepMetrics
         * @description Complete sleep quality metrics for a single sleep period.
         *
         *     Implements Tudor-Locke metrics algorithm as defined in the
         *     actigraph.sleepr R package.
         *
         *     Reference:
         *         Tudor-Locke C, et al. (2014). Fully automated waist-worn accelerometer algorithm
         *         for detecting children's sleep-period time. Applied Physiology, Nutrition, and
         *         Metabolism, 39(1):53-57.
         */
        SleepMetrics: {
            /** In Bed Time */
            in_bed_time?: string | null;
            /** Out Bed Time */
            out_bed_time?: string | null;
            /** Sleep Onset */
            sleep_onset?: string | null;
            /** Sleep Offset */
            sleep_offset?: string | null;
            /** Time In Bed Minutes */
            time_in_bed_minutes?: number | null;
            /** Total Sleep Time Minutes */
            total_sleep_time_minutes?: number | null;
            /** Sleep Onset Latency Minutes */
            sleep_onset_latency_minutes?: number | null;
            /** Waso Minutes */
            waso_minutes?: number | null;
            /** Number Of Awakenings */
            number_of_awakenings?: number | null;
            /** Average Awakening Length Minutes */
            average_awakening_length_minutes?: number | null;
            /** Sleep Efficiency */
            sleep_efficiency?: number | null;
            /** Movement Index */
            movement_index?: number | null;
            /** Fragmentation Index */
            fragmentation_index?: number | null;
            /** Sleep Fragmentation Index */
            sleep_fragmentation_index?: number | null;
            /** Total Activity */
            total_activity?: number | null;
            /** Nonzero Epochs */
            nonzero_epochs?: number | null;
        };
        /**
         * SleepPeriod
         * @description Individual sleep period with onset/offset timestamps.
         *
         *     Ported from desktop's dataclasses_markers.SleepPeriod.
         */
        /**
         * SensorNonwearPeriod
         * @description A nonwear period uploaded from sensor CSV data (read-only overlay).
         */
        SensorNonwearPeriod: {
            /** Start Timestamp */
            start_timestamp: number;
            /** End Timestamp */
            end_timestamp: number;
        };
        SleepPeriod: {
            /** Onset Timestamp */
            onset_timestamp?: number | null;
            /** Offset Timestamp */
            offset_timestamp?: number | null;
            /**
             * Marker Index
             * @default 1
             */
            marker_index: number;
            /** @default MAIN_SLEEP */
            marker_type: components["schemas"]["MarkerType"];
        };
        /**
         * UserSettingsResponse
         * @description Response model for user settings.
         */
        UserSettingsResponse: {
            /** Sleep Detection Rule */
            sleep_detection_rule?: string | null;
            /** Night Start Hour */
            night_start_hour?: string | null;
            /** Night End Hour */
            night_end_hour?: string | null;
            /** Device Preset */
            device_preset?: string | null;
            /** Epoch Length Seconds */
            epoch_length_seconds?: number | null;
            /** Skip Rows */
            skip_rows?: number | null;
            /** Preferred Display Column */
            preferred_display_column?: string | null;
            /** View Mode Hours */
            view_mode_hours?: number | null;
            /** Default Algorithm */
            default_algorithm?: string | null;
            /** Extra Settings */
            extra_settings?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * UserSettingsUpdate
         * @description Request model for updating user settings.
         */
        UserSettingsUpdate: {
            /** Sleep Detection Rule */
            sleep_detection_rule?: string | null;
            /** Night Start Hour */
            night_start_hour?: string | null;
            /** Night End Hour */
            night_end_hour?: string | null;
            /** Device Preset */
            device_preset?: string | null;
            /** Epoch Length Seconds */
            epoch_length_seconds?: number | null;
            /** Skip Rows */
            skip_rows?: number | null;
            /** Preferred Display Column */
            preferred_display_column?: string | null;
            /** View Mode Hours */
            view_mode_hours?: number | null;
            /** Default Algorithm */
            default_algorithm?: string | null;
            /** Extra Settings */
            extra_settings?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationStatus
         * @description Verification status for annotations.
         * @enum {string}
         */
        VerificationStatus: "draft" | "submitted" | "verified" | "disputed" | "resolved";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    auth_status_api_v1_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusResponse"];
                };
            };
        };
    };
    session_login_api_v1_auth_session_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_logout_api_v1_auth_session_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    session_me_api_v1_auth_session_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
    upload_file_api_v1_files_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
                "X-Username"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_files_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_api_v1_files_upload_api_post: {
        parameters: {
            query?: {
                username?: string;
            };
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_api_v1_files_upload_api_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_v1_files_get: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: {
                "X-Site-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_FileInfo_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_files_api_v1_files_delete: {
        parameters: {
            query?: {
                status_filter?: string | null;
            };
            header?: {
                "X-Site-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_v1_files__file_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_api_v1_files__file_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_dates_api_v1_files__file_id__dates_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_data_directory_api_v1_files_scan_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
                "X-Username"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_status_api_v1_files_scan_status_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watcher_status_api_v1_files_watcher_status_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_data_api_v1_activity__file_id___analysis_date__get: {
        parameters: {
            query?: {
                /** @description Hours of data to return (12-48) */
                view_hours?: number;
            };
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_data_with_scoring_api_v1_activity__file_id___analysis_date__score_get: {
        parameters: {
            query?: {
                view_hours?: number;
                /** @description Sleep scoring algorithm to use */
                algorithm?: string;
            };
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_data_with_sadeh_api_v1_activity__file_id___analysis_date__sadeh_get: {
        parameters: {
            query?: {
                view_hours?: number;
            };
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_markers_api_v1_markers__file_id___analysis_date__get: {
        parameters: {
            query?: {
                /** @description Include Sadeh algorithm results */
                include_algorithm?: boolean;
            };
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkersWithMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_markers_api_v1_markers__file_id___analysis_date__put: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
                "X-Username"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkerUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_marker_api_v1_markers__file_id___analysis_date___period_index__delete: {
        parameters: {
            query?: {
                marker_category?: components["schemas"]["MarkerCategory"];
            };
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
                period_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_adjacent_day_markers_api_v1_markers__file_id___analysis_date__adjacent_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdjacentDayMarkersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_onset_offset_data_api_v1_markers__file_id___analysis_date__table__period_index__get: {
        parameters: {
            query?: {
                window_minutes?: number;
            };
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
                period_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnsetOffsetTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_full_table_data_api_v1_markers__file_id___analysis_date__table_full_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FullTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_columns_api_v1_export_columns_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportColumnsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_csv_export_api_v1_export_csv_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_csv_export_api_v1_export_csv_download_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quick_export_api_v1_export_csv_quick_get: {
        parameters: {
            query: {
                /** @description Comma-separated file IDs */
                file_ids: string;
                /** @description Start date filter */
                start_date?: string | null;
                /** @description End date filter */
                end_date?: string | null;
            };
            header?: {
                "X-Site-Password"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diary_entry_api_v1_diary__file_id___analysis_date__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryEntryResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_diary_entry_api_v1_diary__file_id___analysis_date__put: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
                "X-Username"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiaryEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_diary_entry_api_v1_diary__file_id___analysis_date__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
            };
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_diary_csv_api_v1_diary__file_id__upload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
                "X-Username"?: string | null;
            };
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_diary_csv_api_v1_diary__file_id__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
                "X-Username"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
                "X-Username"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_settings_api_v1_settings_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Site-Password"?: string | null;
                "X-Username"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
