"""
Pydantic schemas for the Sleep Scoring Web API.

This package contains all Pydantic models that serve as the
single source of truth for both API validation and OpenAPI generation.
"""

from .enums import (
    AlgorithmType,
    FileStatus,
    MarkerCategory,
    MarkerType,
    NonwearAlgorithm,
    SleepPeriodDetectorType,
    UserRole,
    VerificationStatus,
)
from .models import (
    ActivityDataColumnar,
    ActivityDataResponse,
    AssignmentProgressFile,
    AssignmentProgressResponse,
    AuthMeResponse,
    AutoScoreResultResponse,
    BackfillResponse,
    ComputeComplexityResponse,
    CreateAssignmentsResponse,
    DateStatus,
    DeleteAllFilesResponse,
    DeleteResponse,
    ExportColumnCategory,
    ExportColumnInfo,
    ExportColumnsResponse,
    ExportRequest,
    ExportResponse,
    FileAssignmentResponse,
    FileInfo,
    FileListResponse,
    FileUploadResponse,
    FullTableColumnar,
    FullTableDataPoint,
    FullTableResponse,
    ManualNonwearPeriod,
    MarkerDeleteResponse,
    MarkerResponse,
    MarkerUpdateRequest,
    NightComplexityResponse,
    OnsetOffsetColumnar,
    OnsetOffsetColumnarResponse,
    OnsetOffsetDataPoint,
    OnsetOffsetTableResponse,
    PipelineDiscoveryResponse,
    PurgeExcludedResponse,
    ScanStartResponse,
    ScanStatusResponse,
    SleepMetrics,
    SleepPeriod,
    UnassignedFileResponse,
    WatcherStatusResponse,
)

__all__ = [
    # Models
    "ActivityDataColumnar",
    "ActivityDataResponse",
    # Enums
    "AlgorithmType",
    # Response models
    "AssignmentProgressFile",
    "AssignmentProgressResponse",
    "AuthMeResponse",
    "AutoScoreResultResponse",
    "BackfillResponse",
    "ComputeComplexityResponse",
    "CreateAssignmentsResponse",
    # Date status
    "DateStatus",
    "DeleteAllFilesResponse",
    "DeleteResponse",
    # Export
    "ExportColumnCategory",
    "ExportColumnInfo",
    "ExportColumnsResponse",
    "ExportRequest",
    "ExportResponse",
    # Files
    "FileAssignmentResponse",
    "FileInfo",
    "FileListResponse",
    "FileStatus",
    "FileUploadResponse",
    # Table models
    "FullTableColumnar",
    "FullTableDataPoint",
    "FullTableResponse",
    # Markers
    "ManualNonwearPeriod",
    "MarkerCategory",
    "MarkerDeleteResponse",
    "MarkerResponse",
    "MarkerType",
    "MarkerUpdateRequest",
    "NightComplexityResponse",
    "NonwearAlgorithm",
    "OnsetOffsetColumnar",
    "OnsetOffsetColumnarResponse",
    "OnsetOffsetDataPoint",
    "OnsetOffsetTableResponse",
    "PipelineDiscoveryResponse",
    "PurgeExcludedResponse",
    "ScanStartResponse",
    "ScanStatusResponse",
    "SleepMetrics",
    "SleepPeriod",
    "SleepPeriodDetectorType",
    "UnassignedFileResponse",
    # Auth enums
    "UserRole",
    "VerificationStatus",
    "WatcherStatusResponse",
]
